services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_php
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./config/jwt:/var/www/config/jwt:ro
    environment:
      APP_ENV: dev
      APP_SECRET: issat2026secretkey32charsminimum
      DATABASE_URL: "postgresql://app_user:app_password@db:5432/event_reservation?serverVersion=14&charset=utf8"
      JWT_SECRET_KEY: /var/www/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/config/jwt/public.pem
      JWT_PASSPHRASE: souhq
      JWT_TOKEN_TTL: 3600
      APP_DOMAIN: localhost
      WEBAUTHN_RP_NAME: "EventReservation App"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  nginx:
    image: nginx:1.25-alpine
    container_name: event_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    container_name: event_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: event_reservation
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d event_reservation"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: event_pgadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge