server {
    listen 80;
    server_name localhost;
    root /var/www/public;
    index index.php;

    client_max_body_size 10M;

    # Assets statiques — cache long
    location ~* \.(js|css|png|jpg|jpeg|gif|webp|svg|ico|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }

    # Uploads
    location /uploads/ {
        alias /var/www/public/uploads/;
        try_files $uri =404;
    }

    # Front controller Symfony
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass  php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include       fastcgi_params;
        fastcgi_read_timeout 60;
    }

    # Sécurité : bloquer les fichiers cachés
    location ~ /\.(ht|git|env) {
        deny all;
    }
}
