parameters:
    uploads_dir: '%kernel.project_dir%/public/uploads'
    mailer_from_email: '%env(MAILER_FROM_EMAIL)%'
    mailer_from_name: '%env(MAILER_FROM_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MailService:
        arguments:
            $fromEmail: '%mailer_from_email%'
            $fromName: '%mailer_from_name%'